name: Release

on:
  # Trigger the workflow on the new PVP version tag created.
  # https://pvp.haskell.org/
  # See patterns explanation at:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    name: Haskell-Release - ${{ matrix.os }} - ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 points to x64 based OS and mocos-latest points to arm based OS
        os:
            - ubuntu-latest
            - macos-latest
            - macos-13
        cabal:
            - 3.12.1.0
        ghc:
            - 9.8.2

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
            ghc-version: ${{ matrix.ghc }}
            cabal-version: ${{ matrix.cabal }}

      - name: cache
        uses: actions/cache@v4
        with:
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          path: ~/.cabal/store
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
            ${{ matrix.os }}-${{ matrix.ghc }}-

      - name: Zip data directory
        run: zip -r swarm-data.zip ./data || { echo "Unable to create a zip archive."; exit 1;  }

      - name: Install dependencies
        run: |
          cabal v2-build --disable-tests --disable-benchmarks --dependencies-only -j2 all

      - name: Build binary
        run: |
          mkdir dist
          cabal v2-install exe:swarm --install-method=copy --overwrite-policy=always --installdir=dist

      - name: Set binary path name
        run: echo BINARY_PATH="./dist/swarm" >> "$GITHUB_ENV"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            body_path: ${{ env.BINARY_PATH }}
            name: swarm-${{ runner.os }}
            draft: false
            prerelease: false
            files: |
              LICENSE
              swarm-data.zip

      - name: Generate tarball for Hackage
        run: cabal v2-sdist

      # - name: Generate documentation for Hackage
      #   # The hackage-server attempts to build documentation for library packages, but this can fail.
      #   # If it does we can do it ourselves
      #   run: cabal v2-haddock --builddir=docs --haddock-for-hackage --enable-doc

      # - uses: haskell-actions/hackage-publish@v1
      #   with:
      #     hackageToken: "${{ secrets.HACKAGE_AUTH_TOKEN }}"
      #     packagesPath: dist-newstyle/sdist
      #     # docsPath: docs
      #     publish: true
